import { FormEvent, useState } from "react";
import type { AdminSession } from "./api";
import {
  useExecuteActionMutation,
  useIssueDownloadMutation,
  usePageDataQuery,
  usePrepareActionMutation,
} from "./api";

export function OperationsManagement({ session }: { session: AdminSession }) {
  const operations = usePageDataQuery(
    { page: "operations", search: "" },
    { pollingInterval: 2_000 },
  );
  const [prepare] = usePrepareActionMutation();
  const [execute, execution] = useExecuteActionMutation();
  const [issueDownload, downloadIssuance] = useIssueDownloadMutation();
  const [message, setMessage] = useState("");

  async function enqueue(
    command: string,
    targetId: string,
    input: Record<string, unknown>,
  ) {
    setMessage("");
    try {
      const prepared = await prepare({
        command, target_id: targetId, csrf: session.csrf_token,
      }).unwrap();
      await execute({ prepared, input, csrf: session.csrf_token }).unwrap();
      setMessage(`${command} queued.`);
      await operations.refetch();
    } catch (error) {
      if (isFreshAuthError(error)) {
        const returnPath = window.location.pathname + window.location.search;
        window.location.assign(`/admin/auth/reauth?return=${encodeURIComponent(returnPath)}`);
        return;
      }
      setMessage(`${command} failed.`);
    } finally {
      execution.reset();
    }
  }

  async function download(operationId: string) {
    try {
      const grant = await issueDownload({
        operationId, csrf: session.csrf_token,
      }).unwrap();
      window.location.assign(
        `/api/admin/downloads/${encodeURIComponent(grant.download_handle)}`,
      );
    } catch {
      setMessage("Diagnostics download could not be prepared or was already consumed.");
    } finally {
      downloadIssuance.reset();
    }
  }

  return (
    <section className="mt-4" aria-labelledby="managed-operations-title">
      <h2 className="h4" id="managed-operations-title">Managed operations</h2>
      <p className="text-body-secondary">
        Backup names are generated by the server below its configured root.
        Restore and migration remain CLI-only.
      </p>
      {message && <div className="alert alert-info" role="status">{message}</div>}
      <div className="row g-3">
        <div className="col-lg-4">
          <button
            className="btn btn-outline-primary"
            type="button"
            onClick={() => void enqueue("operations.doctor", "", {})}
          >
            Run doctor
          </button>
        </div>
        <OperationForm
          title="Create backup"
          confirmation="BACKUP"
          onSubmit={(label, reason, confirmation) => enqueue(
            "operations.backup.create", "", { label, reason, confirmation },
          )}
        />
        <OperationForm
          title="Create diagnostics"
          confirmation="DIAGNOSTICS"
          onSubmit={(label, reason, confirmation) => enqueue(
            "operations.diagnostics", "", { label, reason, confirmation },
          )}
        />
      </div>
      <div className="mt-4">
        {operations.data?.items?.map((operation) => (
          <div className="card card-body mb-2" key={operation.id}>
            <div>
              <span className="fw-semibold">{operation.primary}</span>
              <span className="badge text-bg-secondary ms-2">{operation.status}</span>
            </div>
            <div className="d-flex gap-2 mt-2">
              {operation.primary === "backup" && operation.status === "completed" && (
                <button
                  className="btn btn-sm btn-outline-primary"
                  type="button"
                  onClick={() => void enqueue(
                    "operations.backup.verify",
                    operation.id,
                    { reason: "Operator-requested verification", confirmation: "VERIFY" },
                  )}
                >
                  Verify
                </button>
              )}
              {operation.primary === "diagnostics" && operation.status === "completed" && (
                <button
                  className="btn btn-sm btn-outline-primary"
                  type="button"
                  onClick={() => void download(operation.id)}
                >
                  Prepare one-use download
                </button>
              )}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function OperationForm({ title, confirmation, onSubmit }: {
  title: string;
  confirmation: string;
  onSubmit: (label: string, reason: string, confirmation: string) => Promise<void>;
}) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    void onSubmit(
      String(data.get("label") ?? "").trim(),
      String(data.get("reason") ?? "").trim(),
      String(data.get("confirmation") ?? ""),
    ).then(() => form.reset());
  }
  return (
    <form className="col-lg-4" onSubmit={submit}>
      <div className="card card-body h-100">
        <div className="fw-semibold mb-2">{title}</div>
        <input className="form-control mb-2" name="label" maxLength={80} placeholder="Optional label" />
        <input className="form-control mb-2" name="reason" maxLength={500} required placeholder="Operator reason" />
        <input className="form-control font-monospace mb-2" name="confirmation" required placeholder={`Type ${confirmation}`} autoComplete="off" />
        <button className="btn btn-outline-primary" type="submit">{title}</button>
      </div>
    </form>
  );
}

function isFreshAuthError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;
  const candidate = error as { status?: number; data?: { error?: string } };
  return candidate.status === 401 && candidate.data?.error === "fresh_auth_required";
}
